version: "3.9"
services:
  fastapi:
    image: magic-rust-activity-backend
    container_name: magic-rust-activity-backend
    build: .
    restart: "no"
    command: fastapi dev --host 0.0.0.0
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/code

  dramatiq-worker:
    image: magic-rust-activity-backend
    container_name: magic-rust-activity-dramatiq-worker
    build: .
    restart: always
    command: dramatiq app.tasks
    env_file: .env
    volumes:
      - .:/code

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    profiles:
      - services

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    profiles:
      - services

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: ip-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./storage/rabbitmq/data/:/var/lib/rabbitmq/
      - ./storage/rabbitmq/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=activity
    profiles:
      - services

  redis:
    image: redis:7.2-alpine
    restart: on-failure
    ports:
      - '6379:6379'
    volumes:
      - ./storage/redis:/data
